# (a)

In [2]:
import numpy as np
def matrix_sum(A, B):

    if A.shape != B.shape:
        print("Error: Matrices must have the same dimensions for addition.")
    return A+B

A = np.array([[5,2], [2,4]])
B = np.array([[9,6], [3,8]])

Sum = matrix_sum(A, B)
print("A+B:\n", Sum)
    

A+B:
 [[14  8]
 [ 5 12]]


# (b)

In [3]:
import numpy as np
def det_of_matrix(matrix):

    if matrix.shape[0] != matrix.shape[1]:
        print("Must be a square matrix for calculate determinant")
    return np.linalg.det(matrix)

A = np.array([[5, 2], [1, 6]])

det = det_of_matrix(A)
print("Matrix A:\n", A)
print("Determinant of A: ",det)

Matrix A:
 [[5 2]
 [1 6]]
Determinant of A:  27.999999999999996


# (c)

In [14]:
import numpy as np

def transpose_matrix(A):
    return A.T

A = np.array([[3, 4, 1],
              [1, 7, 4]])
transpose = transpose_matrix(A)
print("Transpose of A: \n",transpose)

Transpose of A: 
 [[3 1]
 [4 7]
 [1 4]]


# (d)

In [13]:
import numpy as np

def check_symmetric(A):

    if A.shape[0] != A.shape[1]:
        return False
    return np.array_equal(A, A.T)

A = np.array([[4, 2, 1],
              [2, 8, 5],
              [1, 5, 2]])

print ("Matrix A: \n", A)
print ("Is a symmetric?", check_symmetric(A))

Matrix A: 
 [[4 2 1]
 [2 8 5]
 [1 5 2]]
Is a symmetric? True


# (e)

In [16]:
import numpy as np

def matrix_multiply(A, B):

    if A.shape[1] != B.shape[0]:
        print ("Number of columns must be equal")
    return np.dot(A, B)

A = np.array([[3,2],
              [6,1]])
B = np.array([[2,9],
              [6,2]])

A_dot_B =  matrix_multiply(A, B)
print ("A.B: \n", A_dot_B)
    

A.B: 
 [[18 31]
 [18 56]]
