In [1]:
import numpy as np

def check_symmetric(A):

    if A.shape[0] != A.shape[1]:
        return False
    return np.array_equal(A, A.T)

A = np.array([[2, 1, -3],
              [1, 2, -3],
              [-3, -3, -3]])

print ("Matrix A: \n", A)
print ("Is a symmetric?", check_symmetric(A))

Matrix A: 
 [[ 2  1 -3]
 [ 1  2 -3]
 [-3 -3 -3]]
Is a symmetric? True
